version: '2'
services:

  database:
    image: mongo:3.6.8
    ports:
      - 27017:27017

  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.0
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:5.1.0
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_DELETE_TOPIC_ENABLE=false
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT, OUTSIDE:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9093, OUTSIDE://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9093, OUTSIDE://0.0.0.0:9092
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

  kafka-init:
    image: confluentinc/cp-kafka:5.1.0
    command: |
      bash -c "
        until kafka-topics --create --if-not-exists --zookeeper zookeeper:2181 --replication-factor 1 --partitions 1 --topic chat --config retention.ms=157680000000; do sleep 1; done
      "
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - kafka

  schema-registry:
    image: confluentinc/cp-schema-registry:5.1.0
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
      - SCHEMA_REGISTRY_HOST_NAME=localhost
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
    ports:
      - 8081:8081
    depends_on:
      - kafka
